# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abyssal_conduit.bone.lantern_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_lantern_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abyssal_conduit.bone.lantern_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_lantern_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abyssal_conduit.bone.lantern_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_lantern_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abyssal_conduit.bone.item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_item_display set from storage aj:uuid main.out