# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:abyssal_conduit/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator2.uuid
function animated_java:abyssal_conduit/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator3.uuid
function animated_java:abyssal_conduit/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator4.uuid
function animated_java:abyssal_conduit/zzz/execute with storage aj:temp