# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.breeze.idle_ground player @a ~ ~ ~ 1 2
playsound minecraft:item.trident.return player @a ~ ~ ~ 1 0.5