# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:end_rod ~ ~ ~ 0 0 0 0.6 40
playsound minecraft:block.grindstone.use player @a ~ ~ ~ 1 1.4