# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:item.trident.thunder player @a ~ ~ ~ 1 2
function animated_java:necron_domain/animations/spin/play