# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.thallasion_acid.root] run return 0
execute on passengers if entity @s[tag=aj.thallasion_acid.data] unless data entity @s {data:{rigHash: '30bc0841c2a4485d32fcb0685084e315240ac8f5805c4c1549ee3bd4f4620461'}} on vehicle run function animated_java:thallasion_acid/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1