# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.thallasion_acid.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'thallasion_acid', 'function_path': 'animated_java:thallasion_acid/animations/main/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.main.frame $(frame)
execute at @s run function animated_java:thallasion_acid/animations/main/zzz/apply_frame with storage aj:temp