# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.angler_cod.root] run return 0
execute on passengers if entity @s[tag=aj.angler_cod.data] unless data entity @s {data:{rigHash: '1702fa0af926b529a71578baa607a7948aa5a8081c45926e8e2f0f058e084951'}} on vehicle run function animated_java:angler_cod/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1