# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.necron_eternity_gate.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'necron_eternity_gate', 'function_path': 'animated_java:necron_eternity_gate/animations/erupt/play'}
tag @s add aj.necron_eternity_gate.animation.erupt.playing
scoreboard players set @s aj.erupt.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:necron_eternity_gate/animations/erupt/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only