# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.angler_cod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'angler_cod', 'function_path': 'animated_java:angler_cod/animations/pop/next_frame'}
execute if score @s aj.pop.frame matches 41.. run scoreboard players set @s aj.pop.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.pop.frame
execute at @s run function animated_java:angler_cod/animations/pop/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.pop.frame 1