# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.bonlo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bonlo', 'function_path': 'animated_java:bonlo/animations/shoot_hollow/next_frame'}
execute if score @s aj.shoot_hollow.frame matches 44.. run scoreboard players set @s aj.shoot_hollow.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.shoot_hollow.frame
execute at @s run function animated_java:bonlo/animations/shoot_hollow/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.shoot_hollow.frame 1