# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.bonlo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'bonlo', 'function_path': 'animated_java:bonlo/animations/shoot_hollow/stop'}
tag @s remove aj.bonlo.animation.shoot_hollow.playing
scoreboard players set @s aj.shoot_hollow.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:bonlo/animations/shoot_hollow/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only