# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
stopsound @a player hypno:hollow_purple
stopsound @a player hypno:honored_one
particle minecraft:witch ~ ~1 ~ 0.2 0.3 0.2 1 200
function bonlo:hollow_summon
function animated_java:bonlo/remove/this