# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:plushie_totem/animations/crank/zzz/apply_frame {frame: 200}
scoreboard players add @s aj.crank.frame 1