# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.plushie_totem.root] run return 0
execute on passengers if entity @s[tag=aj.plushie_totem.data] unless data entity @s {data:{rigHash: '3c6e4a20ddfaca84ef2e7c70e4f189c52b735214938f64de6a78ef9e2a353f07'}} on vehicle run function animated_java:plushie_totem/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1