# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.plushie_totem.root] run return 0
execute on passengers if entity @s[tag=aj.plushie_totem.data] unless data entity @s {data:{rigHash: '9607df38c35946f7a7795634c9f6a9f9c4defe5d64c4af2c1b52e194e6a948ed'}} on vehicle run function animated_java:plushie_totem/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1