# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spin.frame dummy
scoreboard objectives add aj.spawn_in.frame dummy
execute as @e[type=item_display,tag=aj.necron_domain.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:necron_domain/root/on_load