name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a108ee6b933162381509084aad253e4da673e80cc816220b09cdb3aaa3925ba"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
