name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e0a787b53b0717c0f745d067a39e5b3316551c2896fd37d1c514b50c7d13042"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
