name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a8a6b4836df7025c9129e3dbf02a2cc0608fd730d0022c2418d803a116d34f"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
