name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5e8c520bc10e43e81b8e454484937c8d1f525224d9ef81815e14152dee82ec8"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
