name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b6bf50e57dec949bd165c1257d8b23a148e2a3c3d6762c0f520069ebefd471b"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
