name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff5b9357d0c2ad605cddf7ae2a54a3f3235487229e9c659cecdcbe52426f39d7"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
