name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "022791fb12245873077ad8cac6a5c01aa37a6899f6975ae37df1cfd732bd13f8"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
