name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074859116df106eb9ca52592f8754330e07ac725523c09041ddf73ca982ffa5f"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
