name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "077a6c67fb389caa8fc2e8ca19c58bfaad0c69c1a7336ee491033f48e1a121fb"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
