name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60494dc65fa1c47b4157d21859c1d83674dcf73cf5513b108c931074b1dff018"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
