name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ffa50da171953ec78627c3d340a9c1fac5820647e65b08b6a50eb3970dacc29"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
