name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a623b84498f38a111808360a1b93ac09653696fd14ba3eae57c91f20ae914a84"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
