name = "Hypno:Origins"
author = "XaNo11"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32302f21bdca073e63eb074d3de1f76718bc0210977ca09bd3b38b9145fe70cf"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
