# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame49] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame49 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame12] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.portal] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_portal set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame13] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame14] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame15] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame16] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame17] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame18] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame19] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame20] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame21] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame22] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame23] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame24] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame24 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.portal1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_portal1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame52] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame52 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame25] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame26] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame27] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame27 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame28] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame28 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame29] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame29 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame30] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame30 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame31] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame31 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame32] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame32 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame33] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame33 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame34] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame34 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame35] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame35 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame36] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame36 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.portal2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_portal2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame51] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame51 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame37] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame37 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame38] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame38 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame39] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame39 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame40] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame40 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame41] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame41 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame42] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame42 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame43] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame43 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame44] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame44 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame45] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame45 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame46] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame46 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame47] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame47 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame48] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame48 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.portal3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_portal3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_eternity_gate.bone.frame50] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_frame50 set from storage aj:uuid main.out