# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.plushie_totem.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'plushie_totem', 'function_path': 'animated_java:plushie_totem/variants/default/apply'}
execute on passengers if entity @s[tag=aj.plushie_totem.bone.leftleg] run function animated_java:plushie_totem/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.plushie_totem.bone.rightleg] run function animated_java:plushie_totem/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.plushie_totem.bone.leftarm] run function animated_java:plushie_totem/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.plushie_totem.bone.rightarm] run function animated_java:plushie_totem/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.plushie_totem.bone.body] run function animated_java:plushie_totem/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.plushie_totem.bone.head] run function animated_java:plushie_totem/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.plushie_totem.bone.crank] run function animated_java:plushie_totem/variants/default/zzz/6