# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.necron_eternity_gate.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'necron_eternity_gate', 'function_path': 'animated_java:necron_eternity_gate/animations/pause_all'}
tag @s remove aj.necron_eternity_gate.animation.erupt.playing
tag @s remove aj.necron_eternity_gate.animation.idle.playing