# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:thallasion_acid/root/zzz/2 with entity @s data.locators.locator
function animated_java:thallasion_acid/root/zzz/4 with entity @s data.locators.locator2
function animated_java:thallasion_acid/root/zzz/6 with entity @s data.locators.locator3
function animated_java:thallasion_acid/root/zzz/8 with entity @s data.locators.locator4