# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.necron_domain.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'necron_domain', 'function_path': 'animated_java:necron_domain/animations/spawn_in/set_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.spawn_in.frame $(frame)
execute at @s run function animated_java:necron_domain/animations/spawn_in/zzz/set_frame with storage aj:temp