# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:block.vault.break player @a ~ ~ ~ 1 0.5
particle minecraft:end_rod ~ ~ ~ 0 0 0 0.1 30
function animated_java:plushie_totem/animations/crank/play