# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spawn_crank.frame dummy
scoreboard objectives add aj.crank.frame dummy
execute as @e[type=item_display,tag=aj.plushie_totem.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:plushie_totem/root/on_load