# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:bonlo/animations/initiate/stop
function animated_java:bonlo/animations/shoot_hollow/play