# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:angler_cod/root/zzz/2 with entity @s data.locators.particle
function animated_java:angler_cod/root/zzz/4 with entity @s data.locators.particle2