# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.pop.frame dummy
scoreboard objectives add aj.idle.frame dummy
execute as @e[type=item_display,tag=aj.angler_cod.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:angler_cod/root/on_load