# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.shot.frame dummy
scoreboard objectives add aj.main.frame dummy
scoreboard objectives add aj.explode.frame dummy