# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:block.grindstone.use player @a ~ ~ ~ 2 0.5
playsound minecraft:block.bell.use player @a ~ ~ ~ 1 0.5