# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:necron_eternity_gate/animations/erupt/stop
function animated_java:necron_eternity_gate/animations/idle/play