# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.base_polished] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_base_polished set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.base_raw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_base_raw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.fragment12] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_fragment12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light_base1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light_base1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light_base3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light_base3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.side_base1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_side_base1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.side_base2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_side_base2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.side_base4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_side_base4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.side_base3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_side_base3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light_base2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light_base2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light_base4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light_base4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light_base5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light_base5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.base_copper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_base_copper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.froglight] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_froglight set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.wave] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_wave set from storage aj:uuid main.out