# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.part5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_part5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.base_polished] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_base_polished set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.base_raw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_base_raw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.pillar4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_pillar4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.light4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_light4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.froglight] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_froglight set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.necron_domain.bone.star1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_star1 set from storage aj:uuid main.out