# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.void_node.root] run return 0
execute on passengers if entity @s[tag=aj.void_node.data] unless data entity @s {data:{rigHash: '39ab34a0782624f56bf57b5e4102294fe9c2e9e4aacacfb80108aa8656d6b4f4'}} on vehicle run function animated_java:void_node/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1