# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.void_node.root] run return 0
execute on passengers if entity @s[tag=aj.void_node.data] unless data entity @s {data:{rigHash: '8c833bb7abc111307b223b4f57b9c4b51f1cfc1b64541df8edf5551bad83441c'}} on vehicle run function animated_java:void_node/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1