# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.abyssal_conduit.root] run return 0
execute on passengers if entity @s[tag=aj.abyssal_conduit.data] unless data entity @s {data:{rigHash: 'a5a445475e07a8913e48325f552dd8a828e90cb46faacb3b68f43b696677be61'}} on vehicle run function animated_java:abyssal_conduit/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1