# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.necron_domain.root] run return 0
execute on passengers if entity @s[tag=aj.necron_domain.data] unless data entity @s {data:{rigHash: '75ec3d83319f36b2899e10b9a37ed728b4cdbba36419270328f3831bd395c885'}} on vehicle run function animated_java:necron_domain/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1