# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.necron_domain.root] run return 0
execute on passengers if entity @s[tag=aj.necron_domain.data] unless data entity @s {data:{rigHash: 'b3eeca5d97b1add418800eb494da0b239057ac71dc4f6767da02f07d120b9af7'}} on vehicle run function animated_java:necron_domain/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1