# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.necron_wave.root] run return 0
execute on passengers if entity @s[tag=aj.necron_wave.data] unless data entity @s {data:{rigHash: 'eb1a1fd9269f2e2d33111a0ad0f9c9f160d4aad412d18fd4a0c653fd8cd58e35'}} on vehicle run function animated_java:necron_wave/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1