# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.thallasion_acid.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'thallasion_acid', 'function_path': 'animated_java:thallasion_acid/animations/explode/next_frame'}
execute if score @s aj.explode.frame matches 26.. run scoreboard players set @s aj.explode.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.explode.frame
execute at @s run function animated_java:thallasion_acid/animations/explode/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.explode.frame 1