# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.necron_eternity_gate.root] run return 0
execute on passengers if entity @s[tag=aj.necron_eternity_gate.data] unless data entity @s {data:{rigHash: 'a09dde91a5e19f3713f03445254f01add59f59c88ffcd0db94bb80d7fa0f0661'}} on vehicle run function animated_java:necron_eternity_gate/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1