# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.necron_eternity_gate.root] run return 0
execute on passengers if entity @s[tag=aj.necron_eternity_gate.data] unless data entity @s {data:{rigHash: 'caa590d3a557ae221f16acbe0d0ced4d1d8aa4bb2026ee135792294f75afa4da'}} on vehicle run function animated_java:necron_eternity_gate/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1