# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.bonlo.root] run return 0
execute on passengers if entity @s[tag=aj.bonlo.data] unless data entity @s {data:{rigHash: '1cb71106ddf39bf1f9ab4eee76e253ce6793b706c82c187d34807a38455f4ea4'}} on vehicle run function animated_java:bonlo/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1