# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.beam7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_beam7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.respawn_anchor] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_respawn_anchor set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.crying_obsidian] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_crying_obsidian set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.void_node.bone.heavy_core] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_heavy_core set from storage aj:uuid main.out