# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:thallasion_acid/animations/main/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.main.frame 1